# Generated by Django 4.2 on 2023-05-10 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItemDeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('pizza', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='firstpizza', to='menu.pizza')),
                ('pizza1', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='secondpizza', to='menu.pizza')),
            ],
        ),
    ]
